<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="Sekhar-PC" failures="1" tests="2" name="IETest" time="63.622" errors="0" timestamp="03 Dec 2019 14:51:46 GMT">
  <testcase classname="TestCases.TC1" name="step1" time="0.208"/>
  <testcase classname="TestCases.TC2" name="step1" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.TC2.step1(TC2.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- step1 -->
  <testcase classname="Base.TestBase" name="@AfterTest teardownTest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest teardownTest -->
  <testcase classname="Base.TestBase" name="@BeforeSuite extentReportSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite extentReportSetup -->
  <testcase classname="TestCases.TC2" name="step2" time="0.0">
    <ignored/>
  </testcase> <!-- step2 -->
  <testcase classname="TestCases.TC1" name="step2" time="0.0">
    <ignored/>
  </testcase> <!-- step2 -->
</testsuite> <!-- IETest -->
